apiVersion: v1
kind: Service
metadata:
  name: db-app
spec:
  selector:
    app: db-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  selector:
    matchLabels:
      app: db-app
  replicas: 1
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
        - name: db-app
          image: db-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret