apiVersion: v1
kind: Service
metadata:
  name: client-app
spec:
  selector:
    app: client-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30008
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
spec:
  selector:
    matchLabels:
      app: client-app
  replicas: 1
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client-app
          image: client-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080